### ISSUE TITLE
RuntimeError: Command `make bootstrap` failed! (code 2)

### ISSUE THREAD

**Issue by armenzg** [getsentry/devenv#53]
### Environment

I received a new MBP M2 (14.1.2 (23B92)).

### Steps to Reproduce

1. Download the script
2. Run it

### Expected Result

Run script to completion

### Actual Result

```
bash install-devenv.sh
Installing dependencies...
Using cached python download...
+ $ /Users/armenzg/.local/share/sentry-devenv/python/bin/python3 -m venv --clear /Users/armenzg/.local/share/sentry-devenv/venv
+ $ /Users/armenzg/.local/share/sentry-devenv/venv/bin/pip install git+https://github.com/getsentry/devenv.git@main
...
--> Creating a superuser account
Added to organization: sentry
User created: admin@sentry.io
Password is admin.
Mocking org Sentry
> Mocking team Massive Dynamic
  > Mocking project Ludic Science
> Mocking team Captain Planet
  > Mocking project Earth
  > Mocking project Fire
  > Mocking project Wind
  > Mocking project Water
  > Mocking project Heart
  ...
--> Building platform assets
--> Finished bootstrapping. Have a nice day.
rm -rf /Users/armenzg/code/getsentry/getsentry/static/CACHE
find . -name '*.pyc' -delete

    ERROR: You're running a virtualenv with Python 3.11.6.
    We only support >= 3.8.10, < 3.9.
    Either run "rm -rf .venv && direnv allow" to
    OR set SENTRY_PYTHON_VERSION=3.11.6 to an .env file to bypass this check."
make: *** [ensure-venv] Error 1
Traceback (most recent call last):
  File "/Users/armenzg/.local/share/sentry-devenv/bin/devenv", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/armenzg/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/main.py", line 137, in main
    return devenv(sys.argv)
           ^^^^^^^^^^^^^^^^
  File "/Users/armenzg/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/main.py", line 101, in devenv
    return bootstrap.main(coderoot, remainder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/armenzg/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/bootstrap.py", line 173, in main
    proc.run(
  File "/Users/armenzg/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/lib/proc.py", line 112, in run
    raise RuntimeError(detail) from None
RuntimeError: Command `make bootstrap` failed! (code 2)
armenzg@JFQDHGQXXM Downloads %
````

**Comment by markushi** [comment]
I'm facing the same issue on a fresh install, any solution for this?
```shell
$ python --version
Python 3.10.13

$ cd sentry 
direnv: loading ~/workspace/sentry/sentry/.envrc
SUCCESS!
direnv: export +NODE_OPTIONS +PIP_DISABLE_PIP_VERSION_CHECK +PYTHONUNBUFFERED +SENTRY_DEVENV_HOME +SENTRY_DEVSERVICES_DSN +SENTRY_UI_HOT_RELOAD +VIRTUAL_ENV +VIRTUAL_ENV_PROMPT +XDG_CACHE_HOME +XDG_CONFIG_DIRS +XDG_CONFIG_HOME +XDG_DATA_DIRS +XDG_DATA_HOME +XDG_RUNTIME_DIR +XDG_STATE_HOME ~PATH
$ python --version
Python 3.11.6
```
