### ISSUE TITLE
devenv sync failed

### ISSUE THREAD

**Issue by armenzg** [getsentry/devenv#57]
I run `devenv sync` since that's what I was recommended after pulling.
I pulled again and was recommended to run `direnv allow` which started installing the latest Python version.

I probably was in this state since the first installation did not go well (see #53).

```
devenv sync
outdated virtualenv version (python 3.8.18)!
creating a new one...
Traceback (most recent call last):
  File "/Users/armenzg/.local/share/sentry-devenv/bin/devenv", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/armenzg/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/main.py", line 137, in main
    return devenv(sys.argv)
           ^^^^^^^^^^^^^^^^
  File "/Users/armenzg/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/main.py", line 120, in devenv
    return sync.main(context, remainder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/armenzg/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/sync.py", line 122, in main
    (pythons.get(python_version, url, sha256), "-m", "venv", venv),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/armenzg/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/pythons.py", line 16, in get
    archive.unpack(archive_file, unpack_into)
  File "/Users/armenzg/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/lib/archive.py", line 47, in unpack
    with tarfile.open(name=path, mode="r:*") as tarf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/armenzg/.local/share/sentry-devenv/python/lib/python3.11/tarfile.py", line 1804, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('invalid header')
- ```

**Comment by asottile-sentry** [comment]
we fixed this already by switching out the zstd archives in sentry: https://github.com/getsentry/sentry/pull/62046
