### ISSUE TITLE
Devenv Bootstrap Fails in Devenv Sync for Non-Sentry Employee

### ISSUE THREAD

**Issue by OCSalter** [getsentry/devenv#60]
### Environment

WSL Ubuntu

### Steps to Reproduce

1. Clone devenv repo
2. Run bash install-devenv.sh
3. run devenv bootstrap, as non-sentry employee

### Expected Result

devenv bootstrap would not fail at resyncing dev environment

### Actual Result
```
Homebrew Bundle complete! 7 Brewfile dependencies now installed.
Resyncing your dev environment.
⏳ git and precommit
Traceback (most recent call last):
  File "/home/odog/.local/share/sentry-devenv/bin/devenv", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/odog/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/main.py", line 152, in main
    return devenv(sys.argv)
           ^^^^^^^^^^^^^^^^
  File "/home/odog/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/main.py", line 135, in devenv
    return sync.main(context, remainder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odog/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/sync.py", line 128, in main
    if not run_procs(
           ^^^^^^^^^^
  File "/home/odog/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/sync.py", line 40, in run_procs
    subprocess.Popen(
  File "/home/odog/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/sentry_sdk/integrations/stdlib.py", line 217, in sentry_patched_popen_init
    rv = old_popen_init(self, *a, **kw)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odog/.local/share/sentry-devenv/python/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/odog/.local/share/sentry-devenv/python/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'make'
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
Traceback (most recent call last):
  File "/home/odog/.local/share/sentry-devenv/bin/devenv", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/odog/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/main.py", line 152, in main
    return devenv(sys.argv)
           ^^^^^^^^^^^^^^^^
  File "/home/odog/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/main.py", line 116, in devenv
    return bootstrap.main(coderoot, remainder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odog/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/bootstrap.py", line 150, in main
    proc.run(("devenv", "sync"), cwd=f"{coderoot}/sentry")
  File "/home/odog/.local/share/sentry-devenv/venv/lib/python3.11/site-packages/devenv/lib/proc.py", line 108, in run
    raise RuntimeError(detail) from None
RuntimeError: Command `devenv sync` failed! (code 1)
```
### Notes

This is my first time trying to contribute to open source so I may just not know what I'm doing

**Comment by joshuarli** [comment]
we don't have official linux support yet but the issue here is you need to install `make`

**Comment by OCSalter** [comment]
Thank you boss 🫡

**Comment by SunnySun1027** [comment]
how to run devenv bootstrap, as non-sentry employee?

**Comment by joshuarli** [comment]
https://github.com/getsentry/devenv#install

**Comment by SunnySun1027** [comment]
> https://github.com/getsentry/devenv#install

I mean that how can I run  bootstrap as non-sentry employee? as run devenv bootstrap always tip me  "Please set the SENTRY_EXTERNAL_CONTRIBUTOR environment variable and re-run bootstrap." But don't know how to set this environment variable? Could you give some steps to me ?

**Comment by OCSalter** [comment]
add ```export SENTRY_EXTERNAL_CONTRIBUTOR=1``` in your .bashrc file (or what ever equivalent you use), so you don't have to add it every time.

**Comment by SunnySun1027** [comment]
So kindly for you! Thanks guys.
